from enum import Enum


class HypothesisID(str, Enum):
    RAIN_OVERWHELM = "RAIN_OVERWHELM"
    DRAIN_BLOCKAGE = "DRAIN_BLOCKAGE"
    POWER_LED_STP_OVERFLOW = "POWER_LED_STP_OVERFLOW"
    PIPE_BURST = "PIPE_BURST"
    LAKE_OVERFLOW = "LAKE_OVERFLOW"
    TRAFFIC_ONLY = "TRAFFIC_ONLY"


class EvidenceKey(str, Enum):
    # Rainfall intensity & history
    RAIN_GT_40 = "RAIN_GT_40"
    RAIN_GT_25 = "RAIN_GT_25"
    RAIN_LT_15 = "RAIN_LT_15"
    RAIN_LT_5 = "RAIN_LT_5"
    SUSTAINED_RAIN_24H = "SUSTAINED_RAIN_24H"
    DRY_WEATHER = "DRY_WEATHER"

    # Geo context
    LOW_LYING = "LOW_LYING"
    KNOWN_HOTSPOT = "KNOWN_HOTSPOT"
    NEAR_LAKE = "NEAR_LAKE"
    LARGE_STP_SITE_NEARBY = "LARGE_STP_SITE_NEARBY"

    # Ticket spatial / temporal patterns
    DEBRIS_TICKETS_NEARBY = "DEBRIS_TICKETS_NEARBY"
    LOCALIZED_SPREAD = "LOCALIZED_SPREAD"
    LINEAR_SPREAD = "LINEAR_SPREAD"
    POWER_TICKETS_PRECEDE_SEWAGE = "POWER_TICKETS_PRECEDE_SEWAGE"

    # External feeds
    OUTAGE_REPORTED = "OUTAGE_REPORTED"
    NO_WATER_POWER_SIGNAL = "NO_WATER_POWER_SIGNAL"
    TRAFFIC_SLOWDOWN = "TRAFFIC_SLOWDOWN"
