import { FC, useState } from 'react';
import { ActionProposal, Incident } from '../../types/api';
import { CheckCircle2, FastForward, Send, ShieldCheck } from 'lucide-react';

interface DispatchConsoleProps {
  incident: Incident | null;
  actions: ActionProposal[];
  onAuthorize: (approvedIds: string[], officer: string) => Promise<void>;
  onVerify: () => Promise<void>;
  isSubmitting: boolean;
}

export const DispatchConsole: FC<DispatchConsoleProps> = ({
  incident,
  actions,
  onAuthorize,
  onVerify,
  isSubmitting,
}) => {
  const [approvedActionIds, setApprovedActionIds] = useState<string[]>(
    actions.map((a, i) => a.id || `act-${i + 1}`)
  );
  const [officerName, setOfficerName] = useState('Chief Disaster Coordinator, BBMP Central Cell');
  const [authorized, setAuthorized] = useState(incident?.status === 'dispatched' || incident?.status === 'resolving' || incident?.status === 'closed');
  const [verifiedResult, setVerifiedResult] = useState<string | null>(null);

  const toggleAction = (id: string) => {
    setApprovedActionIds((prev) =>
      prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]
    );
  };

  const handleAuthorizeClick = async () => {
    await onAuthorize(approvedActionIds, officerName);
    setAuthorized(true);
  };

  const handleVerifyClick = async () => {
    await onVerify();
    setVerifiedResult('Dewatering & feeder restoration validated: Water level reduced to baseline (3cm). Traffic flow on Outer Ring Road restored to 42 km/h freeflow. Status updated to RESOLVING.');
  };

  const departmentTitles: Record<string, { title: string; icon: string }> = {
    stormwater: { title: 'BBMP Stormwater Drain Division (SWD)', icon: '🌧️' },
    traffic_police: { title: 'Bengaluru City Traffic Police (BTP)', icon: '👮' },
    sewerage: { title: 'BWSSB Wastewater & Dewatering Unit', icon: '🚰' },
    power_utility: { title: 'BESCOM Electrical Substation Division', icon: '⚡' },
    solid_waste: { title: 'BBMP Solid Waste Management (SWM)', icon: '🚛' },
    water_board: { title: 'BWSSB Water Supply', icon: '💧' },
  };

  return (
    <div className="space-y-6">
      {/* Console Header */}
      <div className="border-2 border-black bg-surface p-6 md:p-8 space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-borderSubtle pb-4">
          <div>
            <span className="text-[11px] font-mono uppercase text-textMuted tracking-wider block font-bold">
              Municipal Officer HITL Coordination Desk
            </span>
            <h2 className="text-2xl md:text-3xl font-serif font-bold italic text-black tracking-tight mt-1 max-w-5xl">
              Authorize Inter-Agency Municipal Directives
            </h2>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <span className="text-xs font-mono border-2 border-black bg-black text-white px-3 py-1 font-bold">
              {actions.length} DIRECTIVES SYNTHESIZED
            </span>
          </div>
        </div>
        <p className="text-sm text-textBody leading-relaxed max-w-4xl">
          Review emergency orders generated by the planner. Authorizing issues real-time work orders across BBMP, BWSSB, and Bengaluru Traffic Police with immutable evidence justification.
        </p>
      </div>

      {/* Action Orders List with Interactive Checkbox Approval */}
      <div className="space-y-4">
        {actions.map((act, index) => {
          const actId = act.id || `act-${index + 1}`;
          const isApproved = approvedActionIds.includes(actId);
          const deptMeta = departmentTitles[act.dept] || { title: act.dept, icon: '🏛️' };

          return (
            <div
              key={actId}
              className={`border-2 p-5 space-y-3 transition-colors ${
                isApproved ? 'border-black bg-surface' : 'border-borderDark bg-bone opacity-70'
              }`}
            >
              <div className="flex items-center justify-between border-b border-borderSubtle pb-2">
                <div className="flex items-center gap-2.5">
                  <input
                    type="checkbox"
                    checked={isApproved}
                    onChange={() => toggleAction(actId)}
                    className="w-4 h-4 accent-black cursor-pointer"
                  />
                  <span className={`font-mono text-xs font-bold border px-2 py-0.5 ${act.priority === 'P1' ? 'border-red-600 bg-red-100 text-red-700' : 'border-black bg-bone text-black'}`}>
                    {act.priority}
                  </span>
                  <span className="font-serif font-bold italic text-base text-black">
                    {deptMeta.icon} {deptMeta.title}
                  </span>
                </div>
                <div className="text-xs font-mono text-textMuted flex items-center gap-2">
                  <span>ID: <b>{actId}</b></span>
                  <span>Confidence: <b>{Math.round(act.confidence * 100)}%</b></span>
                </div>
              </div>

              <p className="text-sm font-medium text-black leading-relaxed">{act.action}</p>
              <p className="text-xs text-textMuted leading-relaxed">
                <b>Rationale:</b> {act.rationale}
              </p>
              {act.evidence_ids && act.evidence_ids.length > 0 && (
                <div className="text-[11px] font-mono text-textMuted">
                  <b>Evidence Citations:</b> {act.evidence_ids.join(', ')}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Dispatch Authorization Bar */}
      <div className="border-2 border-black bg-bone p-6 md:p-8 space-y-4">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div>
            <h4 className="font-serif font-bold italic text-lg text-black flex items-center gap-2">
              <ShieldCheck className="w-5 h-5 text-black" />
              <span>Officer Digital Sign-off Desk</span>
            </h4>
            <p className="text-xs text-textMuted">
              Requires coordinator digital signature before dispatching cross-agency teams.
            </p>
          </div>

          <div className="w-full md:w-auto">
            <input
              type="text"
              value={officerName}
              onChange={(e) => setOfficerName(e.target.value)}
              className="w-full md:w-80 border border-black p-2 font-mono text-xs bg-white"
              placeholder="Officer Name / Role"
            />
          </div>
        </div>

        <div className="pt-3 border-t border-borderDark flex flex-wrap items-center justify-between gap-3">
          <span className="text-xs font-mono text-textMuted">
            {approvedActionIds.length} of {actions.length} directives selected for immediate dispatch.
          </span>

          <div className="flex items-center gap-3">
            {!authorized ? (
              <button
                onClick={handleAuthorizeClick}
                disabled={isSubmitting || approvedActionIds.length === 0}
                className="border-2 border-black bg-black text-white px-6 py-2.5 font-mono text-xs font-bold uppercase tracking-wider hover:bg-white hover:text-black transition-colors flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
              >
                <Send className="w-4 h-4" />
                {isSubmitting ? 'Issuing Orders...' : 'Authorize & Dispatch Orders'}
              </button>
            ) : (
              <div className="flex flex-wrap items-center gap-3">
                <span className="font-mono text-xs font-bold text-black border border-black bg-white px-3 py-2 flex items-center gap-1.5">
                  <CheckCircle2 className="w-4 h-4 text-black" />
                  Orders Dispatched ({approvedActionIds.length})
                </span>
                <button
                  onClick={handleVerifyClick}
                  disabled={isSubmitting}
                  className="border-2 border-black bg-black text-white hover:bg-white hover:text-black transition-colors px-4 py-2 font-mono text-xs font-bold flex items-center gap-1.5 cursor-pointer"
                >
                  <FastForward className="w-4 h-4" />
                  Fast-Forward 45m & Verify Resolution
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {verifiedResult && (
        <div className="border-2 border-black bg-white p-6 space-y-2">
          <div className="flex items-center gap-2 text-xs font-mono font-bold text-black">
            <CheckCircle2 className="w-4 h-4 text-black" />
            <span>Autonomous Resolution Verification Passed</span>
          </div>
          <p className="text-sm text-textBody">{verifiedResult}</p>
        </div>
      )}
    </div>
  );
};
